<a href="https://colab.research.google.com/github/aryarayz/Nebula/blob/main/Number%20prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np

In [2]:
(X_train, y_train) , (X_test, y_test) = keras.datasets.mnist.load_data()

11493376/11490434 [==============================] - 0s 0us/step


In [3]:
len(X_train)

60000

In [4]:
len(X_test)

10000

In [12]:
X_train.shape

(60000, 28, 28)

In [43]:
X_train = X_train / 255
X_test = X_test / 255

In [ ]:
plt.matshow(X_train[3])

In [44]:
y_train[:5]

array([5, 0, 4, 1, 9], dtype=uint8)

In [45]:
X_tr_flattened = X_train.reshape(len(X_train),28*28)
X_ts_flattened = X_test.reshape(len(X_test),28*28)

In [46]:
X_tr_flattened.shape

(60000, 784)

In [47]:
model = keras.Sequential([
    keras.layers.Dense(10, input_shape=(784,), activation='sigmoid')
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(X_tr_flattened, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.4752 - accuracy: 0.8747
Epoch 2/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.3041 - accuracy: 0.9150
Epoch 3/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.2832 - accuracy: 0.9205
Epoch 4/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.2729 - accuracy: 0.9238
Epoch 5/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.2660 - accuracy: 0.9261


In [48]:
model.evaluate(X_ts_flattened, y_test)

313/313 [==============================] - 0s 1ms/step - loss: 0.2677 - accuracy: 0.9254


[0.2677411735057831, 0.9254000186920166]

In [50]:
model.predict(X_ts_flattened)

array([[1.9520760e-02, 3.7987505e-07, 6.2780529e-02, ..., 9.9976975e-01,
        1.1970219e-01, 6.7456657e-01],
       [3.9601597e-01, 3.5907328e-03, 9.9922949e-01, ..., 1.0283402e-12,
        1.8653175e-01, 1.8989976e-09],
       [3.0699372e-04, 9.9200857e-01, 6.6960937e-01, ..., 1.2212980e-01,
        3.6223036e-01, 3.7864387e-02],
       ...,
       [1.4835369e-06, 3.6721567e-06, 6.9284439e-04, ..., 1.9673932e-01,
        4.8299307e-01, 7.5493908e-01],
       [6.1754443e-05, 1.6537309e-04, 1.0144814e-04, ..., 2.3611557e-05,
        6.1273646e-01, 1.0217255e-04],
       [1.1991382e-02, 3.6800618e-10, 1.2799314e-01, ..., 2.3445432e-08,
        2.6327372e-04, 6.4131592e-07]], dtype=float32)

In [53]:
y_predict = model.predict(X_ts_flattened)
y_predict[0]

array([1.9520760e-02, 3.7987505e-07, 6.2780529e-02, 9.3925428e-01,
       1.6710758e-03, 1.0417715e-01, 1.1460004e-06, 9.9976975e-01,
       1.1970219e-01, 6.7456657e-01], dtype=float32)

In [55]:
np.argmax(y_predict[1])

2